#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
from time import sleep

def kw():
    print("Free money today: https://www.youtube.com/watch?v=dQw4w9WgXcQ\n")
    while True:
        quote = requests.get('https://api.kanye.rest').json()['quote']
        print(f"KANYE: {quote}")
        sleep(5)


if __name__ == '__main__':
    kw()
